#!/usr/bin/env bash

# @(#)Link-My-Desktops.sh	0.1.0	09/04/2015
#
# MIT License
#
# Copyright (c) 2026 Jonathan M. Parker
#
# Permission is hereby granted, free of charge, to any person obtaining a copy
# of this software and associated documentation files (the "Software"), to deal
# in the Software without restriction, including without limitation the rights
# to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
# copies of the Software, and to permit persons to whom the Software is
# furnished to do so, subject to the following conditions:
#
# The above copyright notice and this permission notice shall be included in all
# copies or substantial portions of the Software.
#
# THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
# IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
# FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
# AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
# LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
# OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE
# SOFTWARE.
#
# @author       Jonathan Parker
# @since        0.1.0
# @version      0.1.0
# @updated      $LastChangedDate: 2017-04-04 08:54:30 -0400 (Tue, 04 Apr 2017) $
# @revision     $LastChangedRevision: 6963 $
#
# Usage:
#       Link-My-Desktops.sh

APPLE_DIR="/Library/Desktop Pictures"
MY_DIR="${HOME}/Pictures/My Desktops"

echo "Begin linking my desktop images in ${MY_DIR} to the Apple set in ${APPLE_DIR}..."

sudo ln -s "${MY_DIR}/1920x1200_DallasCast_TNT.jpg" "${APPLE_DIR}/DallasCastTNT.jpg"
sudo ln -s "${MY_DIR}/1920x1200_Dallas_001_TNT.jpg" "${APPLE_DIR}/Dallas001TNT.jpg"
sudo ln -s "${MY_DIR}/1920x1200_Dallas_002_TNT.jpg" "${APPLE_DIR}/Dallas002TNT.jpg"
sudo ln -s "${MY_DIR}/1920x1200_Southfork_001_TNT.jpg" "${APPLE_DIR}/Southfork001TNT.jpg"
sudo ln -s "${MY_DIR}/1920x1200_Southfork_002_TNT.jpg" "${APPLE_DIR}/Southfork002TNT.jpg"
sudo ln -s "${MY_DIR}/1920x1200_Texax_Flag_Dallas_TNT.jpg" "${APPLE_DIR}/TexasFlagDallasTNT.jpg"
sudo ln -s "${MY_DIR}/2009HarvestAtFoxRunVineyards.jpg" "${APPLE_DIR}/HarvestAtFoxRunVineyards.jpg"
sudo ln -s "${MY_DIR}/2012_Hyundai_Veloster_--_01-20-2012_1.jpg" "${APPLE_DIR}/2012HyundaiVelosterRed01.jpg"
sudo ln -s "${MY_DIR}/2012_Hyundai_Veloster_--_01-20-2012_2.jpg" "${APPLE_DIR}/2012HyundaiVelosterRed02.jpg"
sudo ln -s "${MY_DIR}/Fuji.jpg" "${APPLE_DIR}/Fuji01.jpg"
sudo ln -s "${MY_DIR}/Fuji-2.jpg" "${APPLE_DIR}/Fuji02.jpg"
sudo ln -s "${MY_DIR}/Grapes6.jpg" "${APPLE_DIR}/Grapes.jpg"
sudo ln -s "${MY_DIR}/Hyundai-Veloster-price.jpg" "${APPLE_DIR}/2012HyundaiVelosterGreen.jpg"
sudo ln -s "${MY_DIR}/Maryland_Vineyards_at_Fridays_Creek.jpg" "${APPLE_DIR}/MarylandVineyardsAtFridaysCreek.jpg"
sudo ln -s "${MY_DIR}/PrideMountain.JPG" "${APPLE_DIR}/PrideMountain.jpg"
sudo ln -s "${MY_DIR}/Salisbury Vineyards -.jpg" "${APPLE_DIR}/SalisburyVineyards.jpg"
sudo ln -s "${MY_DIR}/Sauvignon_blanc_vlasotince_vineyards.jpg" "${APPLE_DIR}/SauvignonBlancVlasotinceVineyards.jpg"
sudo ln -s "${MY_DIR}/SpringMountainVineyard03.jpg" "${APPLE_DIR}/SpringMountainVineyard03.jpg"
sudo ln -s "${MY_DIR}/SpringMountainVineyard01.jpg" "${APPLE_DIR}/SpringMountainVineyard01.jpg"
sudo ln -s "${MY_DIR}/SpringMountainVineyard02.jpg" "${APPLE_DIR}/SpringMountainVineyard02.jpg"
sudo ln -s "${MY_DIR}/SpringMountainVineyard04.jpg" "${APPLE_DIR}/SpringMountainVineyard04.jpg"
sudo ln -s "${MY_DIR}/SpringMountainVineyard05.jpg" "${APPLE_DIR}/SpringMountainVineyard05.jpg"
sudo ln -s "${MY_DIR}/SpringMountainVineyard06.jpg" "${APPLE_DIR}/SpringMountainVineyard06.jpg"
sudo ln -s "${MY_DIR}/SpringMountainVineyard07.jpg" "${APPLE_DIR}/SpringMountainVineyard07.jpg"
sudo ln -s "${MY_DIR}/SpringMountainVineyard08.jpg" "${APPLE_DIR}/SpringMountainVineyard08.jpg"
sudo ln -s "${MY_DIR}/TopOfTwoCounties.jpg" "${APPLE_DIR}/TopOfTwoCounties.jpg"
sudo ln -s "${MY_DIR}/Vineyard, Napa Valley, California.jpg" "${APPLE_DIR}/VineyardNapaValleyCalifornia.jpg"
sudo ln -s "${MY_DIR}/Wine-Grapes.jpg" "${APPLE_DIR}/WineGrapes01.jpg"
sudo ln -s "${MY_DIR}/camo_1024x768.jpg" "${APPLE_DIR}/ArmyCamo.jpg"
sudo ln -s "${MY_DIR}/crawford2006.JPG" "${APPLE_DIR}/Crawford2006.jpg"
sudo ln -s "${MY_DIR}/dry-stone-vineyards.jpg" "${APPLE_DIR}/DryStoneVineyards.jpg"
sudo ln -s "${MY_DIR}/grape-vines.jpg" "${APPLE_DIR}/GrapeVines.jpg"
sudo ln -s "${MY_DIR}/grapes-vine-wine-vineyard-virginia-farm-field.jpg" "${APPLE_DIR}/VirginiaFarmField.jpg"
sudo ln -s "${MY_DIR}/hillinger-in-the-vineyards-2.jpg" "${APPLE_DIR}/Hillinger.jpg"
sudo ln -s "${MY_DIR}/wine_grapes.jpeg" "${APPLE_DIR}/WineGrapes02.jpg"
sudo ln -s "${MY_DIR}/vineyard.jpg" "${APPLE_DIR}/Vineyard.jpg"
sudo ln -s "${MY_DIR}/ravens_logo01_1024x768.jpg" "${APPLE_DIR}/RavensLogo1.jpg"
sudo ln -s "${MY_DIR}/ravens_logo02_1024x768.jpg" "${APPLE_DIR}/RavensLogo2.jpg"
sudo ln -s "${MY_DIR}/ravens_logo03_1024x768.jpg" "${APPLE_DIR}/RavensLogo3.jpg"
sudo ln -s "${MY_DIR}/star-birth.jpg" "${APPLE_DIR}/StarBirth.jpg"
sudo ln -s "${MY_DIR}/southfork-1.jpg" "${APPLE_DIR}/Southfork1.jpg"
sudo ln -s "${MY_DIR}/southfork-2.jpg" "${APPLE_DIR}/Southfork2.jpg"
sudo ln -s "${MY_DIR}/southfork-3.jpg" "${APPLE_DIR}/Southfork3.jpg"
sudo ln -s "${MY_DIR}/southfork-4.jpg" "${APPLE_DIR}/Southfork4.jpg"
sudo ln -s "${MY_DIR}/sombrero-galaxy.jpg" "${APPLE_DIR}/SombreroGalaxy.jpg"
sudo ln -s "${MY_DIR}/m82-galaxy.jpg" "${APPLE_DIR}/M82Galaxy.jpg"
sudo ln -s "${MY_DIR}/colliding-galaxies.jpg" "${APPLE_DIR}/CollidingGalaxies.jpg"
sudo ln -s "${MY_DIR}/cats-eye-nebula.jpg" "${APPLE_DIR}/CatsEyeNebula.jpg"
sudo ln -s "${MY_DIR}/boomerang-nebula.jpg" "${APPLE_DIR}/BoomerangNebula.jpg"
sudo ln -s "${MY_DIR}/Lined-up-galaxies.jpg" "${APPLE_DIR}/LinedUpGalaxies.jpg"
sudo ln -s "${MY_DIR}/GoghStarryNight11280.jpg" "${APPLE_DIR}/VanGoghStarryNight.jpg"
sudo ln -s "${MY_DIR}/Beach_Life_Widescreen_Wallpapers_02.jpg" "${APPLE_DIR}/BeachLife02.jpg"
sudo ln -s "${MY_DIR}/3726_1600x1200-wallpaper-cb1267712158.jpg" "${APPLE_DIR}/NatGeoWolf.jpg"
sudo ln -s "${MY_DIR}/30723_1600x1200-wallpaper-cb1294082350.jpg" "${APPLE_DIR}/NatGeoWolves.jpg"
sudo ln -s "${MY_DIR}/22665_1600x1200-wallpaper-cb1278691121.jpg" "${APPLE_DIR}/NatGeoJellyFish.jpg"
sudo ln -s "${MY_DIR}/19_Star_Trek_Enterprise_NCC1701D_starship_wallpaper_xx.jpg" "${APPLE_DIR}/StarTrekNCC1701D.jpg"
sudo ln -s "${MY_DIR}/Wolf-Zinn.jpg" "${APPLE_DIR}/Wolf-Zinn.jpg"
sudo ln -s "${MY_DIR}/AU-wp1.jpg" "${APPLE_DIR}/AU-wp1.jpg"
sudo ln -s "${MY_DIR}/AU-wp2.jpg" "${APPLE_DIR}/AU-wp2.jpg"
sudo ln -s "${MY_DIR}/AU-wp3.jpg" "${APPLE_DIR}/AU-wp3.jpg"
sudo ln -s "${MY_DIR}/AU-wp4.jpg" "${APPLE_DIR}/AU-wp4.jpg"
sudo ln -s "${MY_DIR}/AU-wp5.jpg" "${APPLE_DIR}/AU-wp5.jpg"
sudo ln -s "${MY_DIR}/AU-wp6.jpg" "${APPLE_DIR}/AU-wp6.jpg"
sudo ln -s "${MY_DIR}/CA-wp1.jpg" "${APPLE_DIR}/CA-wp1.jpg"
sudo ln -s "${MY_DIR}/CA-wp2.jpg" "${APPLE_DIR}/CA-wp2.jpg"
sudo ln -s "${MY_DIR}/CA-wp3.jpg" "${APPLE_DIR}/CA-wp3.jpg"
sudo ln -s "${MY_DIR}/CA-wp4.jpg" "${APPLE_DIR}/CA-wp4.jpg"
sudo ln -s "${MY_DIR}/CA-wp5.jpg" "${APPLE_DIR}/CA-wp5.jpg"
sudo ln -s "${MY_DIR}/CA-wp6.jpg" "${APPLE_DIR}/CA-wp6.jpg"
sudo ln -s "${MY_DIR}/GB-wp1.jpg" "${APPLE_DIR}/GB-wp1.jpg"
sudo ln -s "${MY_DIR}/GB-wp2.jpg" "${APPLE_DIR}/GB-wp2.jpg"
sudo ln -s "${MY_DIR}/GB-wp3.jpg" "${APPLE_DIR}/GB-wp3.jpg"
sudo ln -s "${MY_DIR}/GB-wp4.jpg" "${APPLE_DIR}/GB-wp4.jpg"
sudo ln -s "${MY_DIR}/GB-wp5.jpg" "${APPLE_DIR}/GB-wp5.jpg"
sudo ln -s "${MY_DIR}/GB-wp6.jpg" "${APPLE_DIR}/GB-wp6.jpg"
sudo ln -s "${MY_DIR}/US-wp1.jpg" "${APPLE_DIR}/US-wp1.jpg"
sudo ln -s "${MY_DIR}/US-wp2.jpg" "${APPLE_DIR}/US-wp2.jpg"
sudo ln -s "${MY_DIR}/US-wp3.jpg" "${APPLE_DIR}/US-wp3.jpg"
sudo ln -s "${MY_DIR}/US-wp4.jpg" "${APPLE_DIR}/US-wp4.jpg"
sudo ln -s "${MY_DIR}/US-wp5.jpg" "${APPLE_DIR}/US-wp5.jpg"
sudo ln -s "${MY_DIR}/US-wp6.jpg" "${APPLE_DIR}/US-wp6.jpg"
sudo ln -s "${MY_DIR}/ZA-wp1.jpg" "${APPLE_DIR}/ZA-wp1.jpg"
sudo ln -s "${MY_DIR}/ZA-wp2.jpg" "${APPLE_DIR}/ZA-wp2.jpg"
sudo ln -s "${MY_DIR}/ZA-wp3.jpg" "${APPLE_DIR}/ZA-wp3.jpg"
sudo ln -s "${MY_DIR}/ZA-wp4.jpg" "${APPLE_DIR}/ZA-wp4.jpg"
sudo ln -s "${MY_DIR}/ZA-wp5.jpg" "${APPLE_DIR}/ZA-wp5.jpg"
sudo ln -s "${MY_DIR}/ZA-wp6.jpg" "${APPLE_DIR}/ZA-wp6.jpg"
sudo ln -s "${MY_DIR}/10_1024x768-wallpaper-cb1267710496.jpg" "${APPLE_DIR}/10_1024x768-wallpaper-cb1267710496.jpg"
sudo ln -s "${MY_DIR}/234_1024x768-wallpaper-cb1267710602.jpg" "${APPLE_DIR}/234_1024x768-wallpaper-cb1267710602.jpg"
sudo ln -s "${MY_DIR}/436_1024x768-wallpaper-cb1267710719.jpg" "${APPLE_DIR}/436_1024x768-wallpaper-cb1267710719.jpg"
sudo ln -s "${MY_DIR}/450_1024x768-wallpaper-cb1267710728.jpg" "${APPLE_DIR}/450_1024x768-wallpaper-cb1267710728.jpg"
sudo ln -s "${MY_DIR}/462_1280x1024-wallpaper-cb1267710734.jpg" "${APPLE_DIR}/462_1280x1024-wallpaper-cb1267710734.jpg"
sudo ln -s "${MY_DIR}/492_1024x768-wallpaper-cb1299003822.jpg" "${APPLE_DIR}/492_1024x768-wallpaper-cb1299003822.jpg"
sudo ln -s "${MY_DIR}/587_1024x768-wallpaper-cb1273177482.jpg" "${APPLE_DIR}/587_1024x768-wallpaper-cb1273177482.jpg"
sudo ln -s "${MY_DIR}/609_1280x1024-wallpaper-cb1289856268.jpg" "${APPLE_DIR}/609_1280x1024-wallpaper-cb1289856268.jpg"
sudo ln -s "${MY_DIR}/611_1280x1024-wallpaper-cb1272903294.jpg" "${APPLE_DIR}/611_1280x1024-wallpaper-cb1272903294.jpg"
sudo ln -s "${MY_DIR}/614_1024x768-wallpaper-cb1331051928.jpg" "${APPLE_DIR}/614_1024x768-wallpaper-cb1331051928.jpg"
sudo ln -s "${MY_DIR}/637_1024x768-wallpaper-cb1281640106.jpg" "${APPLE_DIR}/637_1024x768-wallpaper-cb1281640106.jpg"
sudo ln -s "${MY_DIR}/708_1024x768-wallpaper-cb1267710844.jpg" "${APPLE_DIR}/708_1024x768-wallpaper-cb1267710844.jpg"
sudo ln -s "${MY_DIR}/712_1024x768-wallpaper-cb1281630775.jpg" "${APPLE_DIR}/712_1024x768-wallpaper-cb1281630775.jpg"
sudo ln -s "${MY_DIR}/53922_1600x1200-wallpaper-cb1341259280.jpg" "${APPLE_DIR}/53922_1600x1200-wallpaper-cb1341259280.jpg"
sudo ln -s "${MY_DIR}/56400_1600x1200-wallpaper-cb1342718952.jpg" "${APPLE_DIR}/56400_1600x1200-wallpaper-cb1342718952.jpg"
sudo ln -s "${MY_DIR}/58946_1600x1200-wallpaper-cb1346965323.jpg" "${APPLE_DIR}/58946_1600x1200-wallpaper-cb1346965323.jpg"
sudo ln -s "${MY_DIR}/60067_1600x1200-wallpaper-cb1349989089.jpg" "${APPLE_DIR}/60067_1600x1200-wallpaper-cb1349989089.jpg"
sudo ln -s "${MY_DIR}/61068_1600x1200-wallpaper-cb1352826282.jpg" "${APPLE_DIR}/61068_1600x1200-wallpaper-cb1352826282.jpg"
sudo ln -s "${MY_DIR}/southfork-5.jpg" "${APPLE_DIR}/Southfork5.jpg"
sudo ln -s "${MY_DIR}/southfork-6.jpg" "${APPLE_DIR}/Southfork6.jpg"
sudo ln -s "${MY_DIR}/southfork-7.jpg" "${APPLE_DIR}/Southfork7.jpg"
sudo ln -s "${MY_DIR}/southfork-8.jpg" "${APPLE_DIR}/Southfork8.jpg"
sudo ln -s "${MY_DIR}/southfork-9.jpg" "${APPLE_DIR}/Southfork9.jpg"
sudo ln -s "${MY_DIR}/southfork-10.jpg" "${APPLE_DIR}/Southfork10.jpg"
sudo ln -s "${MY_DIR}/southfork-11.jpg" "${APPLE_DIR}/Southfork11.jpg"
sudo ln -s "${MY_DIR}/MY BALL!_1600x1060.JPG" "${APPLE_DIR}/MY BALL!_1600x1060.JPG"
sudo ln -s "${MY_DIR}/I see you!_1600x859.JPG" "${APPLE_DIR}/I see you!_1600x859.JPG"
sudo ln -s "${MY_DIR}/Big Tongue_1600x1124.JPG" "${APPLE_DIR}/Big Tongue_1600x1124.JPG"
sudo ln -s "${MY_DIR}/Double Trouble_1600x1064.JPG" "${APPLE_DIR}/Double Trouble_1600x1064.JPG"
sudo ln -s "${MY_DIR}/Liger Eyes_1600x1064.JPG" "${APPLE_DIR}/Liger Eyes_1600x1064.JPG"
sudo ln -s "${MY_DIR}/Loka Run_1385x1200.JPG" "${APPLE_DIR}/Loka Run_1385x1200.JPG"
sudo ln -s "${MY_DIR}/Mitra and Chris_1600x978.JPG" "${APPLE_DIR}/Mitra and Chris_1600x978.JPG"
sudo ln -s "${MY_DIR}/Jaga the Lion_1600x1064.JPG" "${APPLE_DIR}/Jaga the Lion_1600x1064.JPG"
sudo ln -s "${MY_DIR}/ZOOM!_1600x831.JPG" "${APPLE_DIR}/ZOOM!_1600x831.JPG"
sudo ln -s "${MY_DIR}/Zeus the Liger_1600x1064.JPG" "${APPLE_DIR}/Zeus the Liger_1600x1064.JPG"
sudo ln -s "${MY_DIR}/Gopal Run_1600x807.JPG" "${APPLE_DIR}/Gopal Run_1600x807.JPG"
sudo ln -s "${MY_DIR}/Gonna Get It!_1600x1130.JPG" "${APPLE_DIR}/Gonna Get It!_1600x1130.JPG"
sudo ln -s "${MY_DIR}/Aries the Liger Baby Swimming_1545x1200.JPG" "${APPLE_DIR}/Aries the Liger Baby Swimming_1545x1200.JPG"
sudo ln -s "${MY_DIR}/Aries the Liger baby_944x1200.JPG" "${APPLE_DIR}/Aries the Liger baby_944x1200.JPG"
sudo ln -s "${MY_DIR}/Govinda and Sloka_1255x1200.JPG" "${APPLE_DIR}/Govinda and Sloka_1255x1200.JPG"
sudo ln -s "${MY_DIR}/Lazy Baby_1600x933.JPG" "${APPLE_DIR}/Lazy Baby_1600x933.JPG"
sudo ln -s "${MY_DIR}/Ojas and his human friends_1506x1200.JPG" "${APPLE_DIR}/Ojas and his human friends_1506x1200.JPG"
sudo ln -s "${MY_DIR}/Ojas and Kody_1600x1097.JPG" "${APPLE_DIR}/Ojas and Kody_1600x1097.JPG"
sudo ln -s "${MY_DIR}/Rahmesh Swimming_1569x1200.JPG" "${APPLE_DIR}/Rahmesh Swimming_1569x1200.JPG"
sudo ln -s "${MY_DIR}/Cat Faces_1600x1069.JPG" "${APPLE_DIR}/Cat Faces_1600x1069.JPG"
sudo ln -s "${MY_DIR}/Tiger Swim_1600x1059.JPG" "${APPLE_DIR}/Tiger Swim_1600x1059.JPG"
sudo ln -s "${MY_DIR}/Tiger Swim 2_1413x1200.JPG" "${APPLE_DIR}/Tiger Swim 2_1413x1200.JPG"
sudo ln -s "${MY_DIR}/Side by Side_1600x1081.JPG" "${APPLE_DIR}/Side by Side_1600x1081.JPG"
sudo ln -s "${MY_DIR}/Liger, Doc, Kody, and Rajani.JPG" "${APPLE_DIR}/Liger, Doc, Kody, and Rajani.JPG"
sudo ln -s "${MY_DIR}/01-simba-east-cubs-zebra-feast_1600.jpg" "${APPLE_DIR}/01-simba-east-cubs-zebra-feast_1600.jpg"
sudo ln -s "${MY_DIR}/03-cboy-serengeti-lion_1600.jpg" "${APPLE_DIR}/03-cboy-serengeti-lion_1600.jpg"
sudo ln -s "${MY_DIR}/07-cboy-hildur-afternoon-rain_1600.jpg" "${APPLE_DIR}/07-cboy-hildur-afternoon-rain_1600.jpg"
sudo ln -s "${MY_DIR}/08-vumbis-rest-on-kopje_1600.jpg" "${APPLE_DIR}/08-vumbis-rest-on-kopje_1600.jpg"
sudo ln -s "${MY_DIR}/11-the-killers-male-coalition_1600.jpg" "${APPLE_DIR}/11-the-killers-male-coalition_1600.jpg"
sudo ln -s "${MY_DIR}/12-cboy-zebra-feast_1600.jpg" "${APPLE_DIR}/12-cboy-zebra-feast_1600.jpg"
sudo ln -s "${MY_DIR}/14-hildur-vumbi-lioness-post-mating-infrared_1600.jpg" "${APPLE_DIR}/14-hildur-vumbi-lioness-post-mating-infrared_1600.jpg"
sudo ln -s "${MY_DIR}/15-females-cross-at-cboy_1600.jpg" "${APPLE_DIR}/15-females-cross-at-cboy_1600.jpg"
sudo ln -s "${MY_DIR}/17-hildur-runs-to-simba-east_1600.jpg" "${APPLE_DIR}/17-hildur-runs-to-simba-east_1600.jpg"
sudo ln -s "${MY_DIR}/19-vumbi-older-cubs_1600.jpg" "${APPLE_DIR}/19-vumbi-older-cubs_1600.jpg"
sudo ln -s "${MY_DIR}/09-smasher-tiger-cools-off_1600.jpg" "${APPLE_DIR}/09-smasher-tiger-cools-off_1600.jpg"
sudo ln -s "${MY_DIR}/11-captive-tigers-play-with-each-other_1600.jpg" "${APPLE_DIR}/11-captive-tigers-play-with-each-other_1600.jpg"
sudo ln -s "${MY_DIR}/14-mother-rests-with-cub_1600.jpg" "${APPLE_DIR}/14-mother-rests-with-cub_1600.jpg"
sudo ln -s "${MY_DIR}/18-tiger-cub-bats-remote-controlled-camera_1600.jpg" "${APPLE_DIR}/18-tiger-cub-bats-remote-controlled-camera_1600.jpg"
sudo ln -s "${MY_DIR}/01-tiger-looks-at-camera-sumatra_1600.jpg" "${APPLE_DIR}/01-tiger-looks-at-camera-sumatra_1600.jpg"
sudo ln -s "${MY_DIR}/07-slips-through-fence-bandhavgarh-national-park_1600.jpg" "${APPLE_DIR}/07-slips-through-fence-bandhavgarh-national-park_1600.jpg"
sudo ln -s "${MY_DIR}/PenguinWallpaper_1920x1080.jpg" "${APPLE_DIR}/PenguinWallpaper_1920x1080.jpg"
sudo ln -s "${MY_DIR}/PolarBearWallpaper_1920x1080.jpg" "${APPLE_DIR}/PolarBearWallpaper_1920x1080.jpg"
sudo ln -s "${MY_DIR}/RedPandaWallpaper_1920x1080.jpg" "${APPLE_DIR}/RedPandaWallpaper_1920x1080.jpg"
sudo ln -s "${MY_DIR}/TigerWallpaper_1920x1080.jpg" "${APPLE_DIR}/TigerWallpaper_1920x1080.jpg"
sudo ln -s "${MY_DIR}/Highclere-1.jpg" "${APPLE_DIR}/Highclere-1.jpg"
sudo ln -s "${MY_DIR}/Highclere-2.jpg" "${APPLE_DIR}/Highclere-2.jpg"
sudo ln -s "${MY_DIR}/Highclere-3.jpg" "${APPLE_DIR}/Highclere-3.jpg"
sudo ln -s "${MY_DIR}/Highclere-4.jpg" "${APPLE_DIR}/Highclere-4.jpg"
sudo ln -s "${MY_DIR}/Highclere-5.jpg" "${APPLE_DIR}/Highclere-5.jpg"
sudo ln -s "${MY_DIR}/Highclere-6.jpg" "${APPLE_DIR}/Highclere-6.jpg"
sudo ln -s "${MY_DIR}/Highclere-7.jpg" "${APPLE_DIR}/Highclere-7.jpg"
sudo ln -s "${MY_DIR}/Highclere-8.jpg" "${APPLE_DIR}/Highclere-8.jpg"
sudo ln -s "${MY_DIR}/Yosemite.jpg" "${APPLE_DIR}/Yosemite.jpg"
sudo ln -s "${MY_DIR}/Yosemite2.jpg" "${APPLE_DIR}/Yosemite2.jpg"
sudo ln -s "${MY_DIR}/Yosemite3.jpg" "${APPLE_DIR}/Yosemite3.jpg"
sudo ln -s "${MY_DIR}/Yosemite4.jpg" "${APPLE_DIR}/Yosemite4.jpg"
sudo ln -s "${MY_DIR}/Yosemite5.jpg" "${APPLE_DIR}/Yosemite5.jpg"
sudo ln -s "${MY_DIR}/2005_ferrari_design_competition_f_zero.jpg" "${APPLE_DIR}/2005_ferrari_design_competition_f_zero.jpg"
sudo ln -s "${MY_DIR}/2010_ferrari_458_italia.jpg" "${APPLE_DIR}/2010_ferrari_458_italia.jpg"
sudo ln -s "${MY_DIR}/2010_ferrari_599_gtb_hy_kers_concept.jpg" "${APPLE_DIR}/2010_ferrari_599_gtb_hy_kers_concept.jpg"
sudo ln -s "${MY_DIR}/2011_ferrari_458_challenge.jpg" "${APPLE_DIR}/2011_ferrari_458_challenge.jpg"
sudo ln -s "${MY_DIR}/2011_ferrari_599_gto.jpg" "${APPLE_DIR}/2011_ferrari_599_gto.jpg"
sudo ln -s "${MY_DIR}/2012_ferrari_ff.jpg" "${APPLE_DIR}/2012_ferrari_ff.jpg"
sudo ln -s "${MY_DIR}/2014_ferrari_f12_berlinetta_n_largo_by_novitec_rosso.jpg" "${APPLE_DIR}/2014_ferrari_f12_berlinetta_n_largo_by_novitec_rosso.jpg"
sudo ln -s "${MY_DIR}/2014_novitec_rosso_ferrari_f12_berlinetta_n_largo.jpg" "${APPLE_DIR}/2014_novitec_rosso_ferrari_f12_berlinetta_n_largo.jpg"
sudo ln -s "${MY_DIR}/2015_ferrari_458_speciale_a.jpg" "${APPLE_DIR}/2015_ferrari_458_speciale_a.jpg"
sudo ln -s "${MY_DIR}/2015_ferrari_488_gtb.jpg" "${APPLE_DIR}/2015_ferrari_488_gtb.jpg"
sudo ln -s "${MY_DIR}/2015_ferrari_fxx_k.jpg" "${APPLE_DIR}/2015_ferrari_fxx_k.jpg"
sudo ln -s "${MY_DIR}/adv1_ferrari_f430.jpg" "${APPLE_DIR}/adv1_ferrari_f430.jpg"
sudo ln -s "${MY_DIR}/amazing_ferrari.jpg" "${APPLE_DIR}/amazing_ferrari.jpg"
sudo ln -s "${MY_DIR}/ferrari-GTES-front1.jpg" "${APPLE_DIR}/ferrari-GTES-front1.jpg"
sudo ln -s "${MY_DIR}/ferrari-GTES-front2.jpg" "${APPLE_DIR}/ferrari-GTES-front2.jpg"
sudo ln -s "${MY_DIR}/ferrari-GTES-front3.jpg" "${APPLE_DIR}/ferrari-GTES-front3.jpg"
sudo ln -s "${MY_DIR}/ferrari-GTES-rear1.jpg" "${APPLE_DIR}/ferrari-GTES-rear1.jpg"
sudo ln -s "${MY_DIR}/ferrari-GTES-rear2.jpg" "${APPLE_DIR}/ferrari-GTES-rear2.jpg"
sudo ln -s "${MY_DIR}/ferrari-GTES-side1.jpg" "${APPLE_DIR}/ferrari-GTES-side1.jpg"
sudo ln -s "${MY_DIR}/ferrari-GTES-side2.jpg" "${APPLE_DIR}/ferrari-GTES-side2.jpg"
sudo ln -s "${MY_DIR}/ferrari-GTES-side3.jpg" "${APPLE_DIR}/ferrari-GTES-side3.jpg"
sudo ln -s "${MY_DIR}/ferrari_430_scuderia_3.jpg" "${APPLE_DIR}/ferrari_430_scuderia_3.jpg"
sudo ln -s "${MY_DIR}/ferrari_458_challenge_2011.jpg" "${APPLE_DIR}/ferrari_458_challenge_2011.jpg"
sudo ln -s "${MY_DIR}/ferrari_458_italia.jpg" "${APPLE_DIR}/ferrari_458_italia.jpg"
sudo ln -s "${MY_DIR}/ferrari_458_italia_hd_wide.jpg" "${APPLE_DIR}/ferrari_458_italia_hd_wide.jpg"
sudo ln -s "${MY_DIR}/ferrari_458_speciale_2014.jpg" "${APPLE_DIR}/ferrari_458_speciale_2014.jpg"
sudo ln -s "${MY_DIR}/ferrari_458_spider.jpg" "${APPLE_DIR}/ferrari_458_spider.jpg"
sudo ln -s "${MY_DIR}/ferrari_458_spider_2012.jpg" "${APPLE_DIR}/ferrari_458_spider_2012.jpg"
sudo ln -s "${MY_DIR}/ferrari_599_gtb.jpg" "${APPLE_DIR}/ferrari_599_gtb.jpg"
sudo ln -s "${MY_DIR}/ferrari_599_gto_2011.jpg" "${APPLE_DIR}/ferrari_599_gto_2011.jpg"
sudo ln -s "${MY_DIR}/ferrari_concept_car.jpg" "${APPLE_DIR}/ferrari_concept_car.jpg"
sudo ln -s "${MY_DIR}/ferrari_enzo.jpg" "${APPLE_DIR}/ferrari_enzo.jpg"
sudo ln -s "${MY_DIR}/ferrari_f12berlinetta.jpg" "${APPLE_DIR}/ferrari_f12berlinetta.jpg"
sudo ln -s "${MY_DIR}/ferrari_f430_adv1.jpg" "${APPLE_DIR}/ferrari_f430_adv1.jpg"
sudo ln -s "${MY_DIR}/ferrari_f430_adv1_wheels.jpg" "${APPLE_DIR}/ferrari_f430_adv1_wheels.jpg"
sudo ln -s "${MY_DIR}/ferrari_f430_red.jpg" "${APPLE_DIR}/ferrari_f430_red.jpg"
sudo ln -s "${MY_DIR}/ferrari_laferrari_2013.jpg" "${APPLE_DIR}/ferrari_laferrari_2013.jpg"
sudo ln -s "${MY_DIR}/ferrari_on_forged_cf_5_wheels.jpg" "${APPLE_DIR}/ferrari_on_forged_cf_5_wheels.jpg"
sudo ln -s "${MY_DIR}/ferrari_red_car.jpg" "${APPLE_DIR}/ferrari_red_car.jpg"
sudo ln -s "${MY_DIR}/ferrari_scuderia_spider_16m_11.jpg" "${APPLE_DIR}/ferrari_scuderia_spider_16m_11.jpg"
sudo ln -s "${MY_DIR}/ferrari_scuderia_spider_16m_4.jpg" "${APPLE_DIR}/ferrari_scuderia_spider_16m_4.jpg"
sudo ln -s "${MY_DIR}/ferrari_scuderia_spider_hdtv_1080p.jpg" "${APPLE_DIR}/ferrari_scuderia_spider_hdtv_1080p.jpg"
sudo ln -s "${MY_DIR}/ferrari_super_car_concept.jpg" "${APPLE_DIR}/ferrari_super_car_concept.jpg"
sudo ln -s "${MY_DIR}/lb_performance_ferrari_458_italia.jpg" "${APPLE_DIR}/lb_performance_ferrari_458_italia.jpg"
sudo ln -s "${MY_DIR}/novitec_rosso_ferrari_f12berlinette.jpg" "${APPLE_DIR}/novitec_rosso_ferrari_f12berlinette.jpg"
sudo ln -s "${MY_DIR}/oakley_design_ferrari_458_italia.jpg" "${APPLE_DIR}/oakley_design_ferrari_458_italia.jpg"
sudo ln -s "${MY_DIR}/sexy_ferrari_italia_car.jpg" "${APPLE_DIR}/sexy_ferrari_italia_car.jpg"
sudo ln -s "${MY_DIR}/touring_superleggera_ferrari_f12_berlinetta_lusso.jpg" "${APPLE_DIR}/touring_superleggera_ferrari_f12_berlinetta_lusso.jpg"
sudo ln -s "${MY_DIR}/white_ferrari_430_scuderia.jpg" "${APPLE_DIR}/white_ferrari_430_scuderia.jpg"
sudo ln -s "${MY_DIR}/white_huracan_web_1.jpeg" "${APPLE_DIR}/white_huracan_web_1.jpeg"
sudo ln -s "${MY_DIR}/white_huracan_web_2.jpeg" "${APPLE_DIR}/white_huracan_web_2.jpeg"
sudo ln -s "${MY_DIR}/gialla_ambientata_1.jpg" "${APPLE_DIR}/gialla_ambientata_1.jpg"
sudo ln -s "${MY_DIR}/gialla_ambientata_2.jpg" "${APPLE_DIR}/gialla_ambientata_2.jpg"
sudo ln -s "${MY_DIR}/huracan_front_view_ov1.jpg" "${APPLE_DIR}/huracan_front_view_ov1.jpg"
sudo ln -s "${MY_DIR}/huracan_rear_view_ov2.jpg" "${APPLE_DIR}/huracan_rear_view_ov2.jpg"
sudo ln -s "${MY_DIR}/huracan_side_view_ov4.jpg" "${APPLE_DIR}/huracan_side_view_ov4.jpg"
sudo ln -s "${MY_DIR}/huracan_top_view_ov2.jpg" "${APPLE_DIR}/huracan_top_view_ov2.jpg"
sudo ln -s "${MY_DIR}/huracan_white_3.jpeg" "${APPLE_DIR}/huracan_white_3.jpeg"
sudo ln -s "${MY_DIR}/huracan_interior.jpeg" "${APPLE_DIR}/huracan_interior.jpeg"
sudo ln -s "${MY_DIR}/img0.jpg" "${APPLE_DIR}/img0.jpg"
sudo ln -s "${MY_DIR}/img1.jpg" "${APPLE_DIR}/img1.jpg"
sudo ln -s "${MY_DIR}/img2.jpg" "${APPLE_DIR}/img2.jpg"
sudo ln -s "${MY_DIR}/img3.jpg" "${APPLE_DIR}/img3.jpg"
sudo ln -s "${MY_DIR}/img4.jpg" "${APPLE_DIR}/img4.jpg"
sudo ln -s "${MY_DIR}/Biltmore-01.jpg" "${APPLE_DIR}/Biltmore-01.jpg"
sudo ln -s "${MY_DIR}/Biltmore-02.jpg" "${APPLE_DIR}/Biltmore-02.jpg"
sudo ln -s "${MY_DIR}/Biltmore-03.jpg" "${APPLE_DIR}/Biltmore-03.jpg"
sudo ln -s "${MY_DIR}/Biltmore-04.jpg" "${APPLE_DIR}/Biltmore-04.jpg"
sudo ln -s "${MY_DIR}/Biltmore-05.jpg" "${APPLE_DIR}/Biltmore-05.jpg"
sudo ln -s "${MY_DIR}/Biltmore-06.jpg" "${APPLE_DIR}/Biltmore-06.jpg"

echo "Done linking my desktop images in ${MY_DIR} to the Apple set in ${APPLE_DIR}."
exit 0
